# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['src/api/server.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('src/humitron', 'humitron'),
        ('config.yaml', '.'),
        ('README.md', '.'),
    ],
    hiddenimports=[
        'humitron',
        'humitron.agent',
        'humitron.config',
        'humitron.config.loader',
        'humitron.memory',
        'humitron.memory.conversation',
        'humitron.tools',
        'humitron.tools.file_ops',
        'humitron.tools.bash',
        'humitron.tools.web',
        'humitron.tools.registry',
        'humitron.models',
        'humitron.models.tools',
        'humitron.models.agent',
        'humitron.utils',
        'humitron.utils.logging',
        'humitron.utils.safety',
        'humitron.orchestrator',
        'humitron.orchestrator.planner',
        'humitron.mcp',
        'humitron.mcp.client',
        'humitron.observability',
        'humitron.observability.trajectory',
        'humitron.performance',
        'humitron.performance.token_budget',
        'pydantic',
        'pydantic_settings',
        'yaml',
        'httpx',
        'rich',
        'loguru',
        'fastapi',
        'uvicorn',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan.on',
        'starlette',
        'starlette.middleware.cors',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='humitron-backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='src-tauri/icons/icon.ico' if os.name == 'nt' else 'src-tauri/icons/icon.icns',
)